package com.jinsong.mapper;

import com.jinsong.model.Engineer;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface EngineerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int insert(Engineer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    Engineer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    List<Engineer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int updateByPrimaryKey(Engineer record);
}