package com.jinsong.mapper;

import com.jinsong.model.Error;
import java.util.List;

public interface ErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int insert(Error record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    Error selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    List<Error> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int updateByPrimaryKey(Error record);
}