package com.jinsong.mapper;

import com.jinsong.model.Factory;
import java.util.List;

public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    Factory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    List<Factory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    int updateByPrimaryKey(Factory record);
}