package com.jinsong.mapper;

import com.jinsong.model.Factory;
import com.jinsong.model.Install;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Sun Apr 08 11:42:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Sun Apr 08 11:42:09 CST 2018
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Sun Apr 08 11:42:09 CST 2018
     */
    Factory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Sun Apr 08 11:42:09 CST 2018
     */
    List<Factory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated Sun Apr 08 11:42:09 CST 2018
     */
    int updateByPrimaryKey(Factory record);
    
    /**
     * 通过serial_number来搜索Factory
     */
    List<Factory> selectBySearch(String searchInfo);
}