package com.jinsong.mapper;

import com.jinsong.model.Image;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    Image selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    List<Image> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int updateByPrimaryKey(Image record);

    /**
     * 根据工单号获取所有对应的图片
     */
    List<Image> selectAllByOrderNumber(String orderNumber);
}