package com.jinsong.mapper;

import com.jinsong.model.Install;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface InstallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install
     *
     * @mbg.generated Sun Feb 25 11:59:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install
     *
     * @mbg.generated Sun Feb 25 11:59:09 CST 2018
     */
    int insert(Install record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install
     *
     * @mbg.generated Sun Feb 25 11:59:09 CST 2018
     */
    Install selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install
     *
     * @mbg.generated Sun Feb 25 11:59:09 CST 2018
     */
    List<Install> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table install
     *
     * @mbg.generated Sun Feb 25 11:59:09 CST 2018
     */
    int updateByPrimaryKey(Install record);
}