package com.jinsong.mapper;

import com.jinsong.model.Maintain;
import java.util.List;

public interface MaintainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int insert(Maintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    Maintain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    List<Maintain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    int updateByPrimaryKey(Maintain record);
}