package com.jinsong.mapper;

import com.jinsong.model.Maintain;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MaintainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Tue Feb 13 15:45:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Tue Feb 13 15:45:39 CST 2018
     */
    int insert(Maintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Tue Feb 13 15:45:39 CST 2018
     */
    Maintain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Tue Feb 13 15:45:39 CST 2018
     */
    List<Maintain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maintain
     *
     * @mbg.generated Tue Feb 13 15:45:39 CST 2018
     */
    int updateByPrimaryKey(Maintain record);
    
    /**
     * 通过hospital_name或者engineer来搜索repair工单
     */
    List<Maintain> selectBySearch(String searchInfo);
}