package com.jinsong.mapper;

import com.jinsong.model.Work;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    Work selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    List<Work> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    int updateByPrimaryKey(Work record);

    /**
     * 根据attendanceTime获得对应的记录
     */
    List<Work> selectAllByAttendanceTime(String attendanceTime);
}