package com.jinsong.model;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.passsword
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String passsword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.gmt_create
     *
     * @return the value of admin.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.gmt_create
     *
     * @param gmtCreate the value for admin.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.gmt_modified
     *
     * @return the value of admin.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.gmt_modified
     *
     * @param gmtModified the value for admin.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account
     *
     * @return the value of admin.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account
     *
     * @param account the value for admin.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.passsword
     *
     * @return the value of admin.passsword
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getPasssword() {
        return passsword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.passsword
     *
     * @param passsword the value for admin.passsword
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setPasssword(String passsword) {
        this.passsword = passsword;
    }
}