package com.jinsong.model;

import java.util.Date;

public class Engineer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String engineer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column engineer.password
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.id
     *
     * @return the value of engineer.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.id
     *
     * @param id the value for engineer.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.gmt_create
     *
     * @return the value of engineer.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.gmt_create
     *
     * @param gmtCreate the value for engineer.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.gmt_modified
     *
     * @return the value of engineer.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.gmt_modified
     *
     * @param gmtModified the value for engineer.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.engineer
     *
     * @return the value of engineer.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.engineer
     *
     * @param engineer the value for engineer.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setEngineer(String engineer) {
        this.engineer = engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.tel
     *
     * @return the value of engineer.tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.tel
     *
     * @param tel the value for engineer.tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.account
     *
     * @return the value of engineer.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.account
     *
     * @param account the value for engineer.account
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column engineer.password
     *
     * @return the value of engineer.password
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column engineer.password
     *
     * @param password the value for engineer.password
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}