package com.jinsong.model;

import java.util.Date;

public class Error {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.phenomenon
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String phenomenon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.reason
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.solution
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String solution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String productModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.error_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String errorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String engineer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.product_version
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String productVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.replace_name_code
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String replaceNameCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.month_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Integer monthSampleCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error.day_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Integer daySampleCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.id
     *
     * @return the value of error.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.id
     *
     * @param id the value for error.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.gmt_create
     *
     * @return the value of error.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.gmt_create
     *
     * @param gmtCreate the value for error.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.gmt_modified
     *
     * @return the value of error.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.gmt_modified
     *
     * @param gmtModified the value for error.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.serial_number
     *
     * @return the value of error.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.serial_number
     *
     * @param serialNumber the value for error.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.time
     *
     * @return the value of error.time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.time
     *
     * @param time the value for error.time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.phenomenon
     *
     * @return the value of error.phenomenon
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getPhenomenon() {
        return phenomenon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.phenomenon
     *
     * @param phenomenon the value for error.phenomenon
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setPhenomenon(String phenomenon) {
        this.phenomenon = phenomenon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.reason
     *
     * @return the value of error.reason
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.reason
     *
     * @param reason the value for error.reason
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.solution
     *
     * @return the value of error.solution
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.solution
     *
     * @param solution the value for error.solution
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSolution(String solution) {
        this.solution = solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.product_model
     *
     * @return the value of error.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.product_model
     *
     * @param productModel the value for error.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setProductModel(String productModel) {
        this.productModel = productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.error_type
     *
     * @return the value of error.error_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.error_type
     *
     * @param errorType the value for error.error_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setErrorType(String errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.engineer
     *
     * @return the value of error.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.engineer
     *
     * @param engineer the value for error.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setEngineer(String engineer) {
        this.engineer = engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.product_version
     *
     * @return the value of error.product_version
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getProductVersion() {
        return productVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.product_version
     *
     * @param productVersion the value for error.product_version
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setProductVersion(String productVersion) {
        this.productVersion = productVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.replace_name_code
     *
     * @return the value of error.replace_name_code
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getReplaceNameCode() {
        return replaceNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.replace_name_code
     *
     * @param replaceNameCode the value for error.replace_name_code
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setReplaceNameCode(String replaceNameCode) {
        this.replaceNameCode = replaceNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.month_sample_count
     *
     * @return the value of error.month_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Integer getMonthSampleCount() {
        return monthSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.month_sample_count
     *
     * @param monthSampleCount the value for error.month_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setMonthSampleCount(Integer monthSampleCount) {
        this.monthSampleCount = monthSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error.day_sample_count
     *
     * @return the value of error.day_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Integer getDaySampleCount() {
        return daySampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error.day_sample_count
     *
     * @param daySampleCount the value for error.day_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setDaySampleCount(Integer daySampleCount) {
        this.daySampleCount = daySampleCount;
    }
}