package com.jinsong.model;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.order_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.img_url
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.order_number
     *
     * @return the value of image.order_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.order_number
     *
     * @param orderNumber the value for image.order_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.img_url
     *
     * @return the value of image.img_url
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.img_url
     *
     * @param imgUrl the value for image.img_url
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
}