package com.jinsong.model;

import java.util.Date;

public class Install {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String engineer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.engineer_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String engineerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.estimated_arrival_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date estimatedArrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.arrivaled_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date arrivaledTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.order_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.finishe_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Date finisheTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hospital_name
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hospital_department
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hospitalDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hospital_address
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hospitalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.zip_code
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.product_type
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hospital_contact
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hospitalContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hospital_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hospitalTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.serial_number
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.product_model
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String productModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.packaging
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String packaging;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.out_appearance
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String outAppearance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.lis
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String lis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.ip
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.install_stauts
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String installStauts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_return_purchase
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isReturnPurchase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isMonitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isComputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_return_status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isReturnStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_microscope
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isMicroscope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_liquid
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isLiquid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_pinch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isPinch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_auto_identify
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isAutoIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_step_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isStepMotor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_micro_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isMicroSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_gold
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_dc_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isDcMotor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_opto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isOpto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_stool_trait
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isStoolTrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_peristaltic_pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isPeristalticPump;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_piston pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isPistonPump;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_stool_color
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isStoolColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_import_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isImportSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_expose_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isExposeSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_cross_pollution
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isCrossPollution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_counting_pool
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isCountingPool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_mix_system
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isMixSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_power_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isPowerBox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_d15
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isD15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_electric_auto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isElectricAuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_electirc_circuit
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isElectircCircuit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.is_buck
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private Byte isBuck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.zero_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String zeroVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.app_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hard_disk
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hardDisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.computer_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String computerVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.cpu
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String cpu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.cd
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.ram
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String ram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.supply_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String supplyVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.computer_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String computerVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.waste_liquid_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String wasteLiquidBucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.card_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String cardBox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.video_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String videoCable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.diluent_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String diluentBucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.instrument_power_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String instrumentPowerCable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.usb_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String usbCable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.clean_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String cleanBucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.computer_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String computerCable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.certificate
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String certificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.maintenance_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String maintenanceBucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.monitor_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String monitorCable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.instrument
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String instrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.manual
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String manual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String computer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String monitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.sample_holder
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String sampleHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.mouse
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String mouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.keyboard
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String keyboard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.supplies
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String supplies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.silicone_tube
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String siliconeTube;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.whether_doa
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String whetherDoa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.doa_information
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String doaInformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hardware
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hardware;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.hardware_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String hardwareReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.teacher_operator
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String teacherOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.teacher_operator_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String teacherOperatorReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.operation_condition
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String operationCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.operation_condition_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String operationConditionReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.client_feedback
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String clientFeedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install.remarks
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.id
     *
     * @return the value of install.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.id
     *
     * @param id the value for install.id
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.gmt_create
     *
     * @return the value of install.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.gmt_create
     *
     * @param gmtCreate the value for install.gmt_create
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.gmt_modified
     *
     * @return the value of install.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.gmt_modified
     *
     * @param gmtModified the value for install.gmt_modified
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.engineer
     *
     * @return the value of install.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.engineer
     *
     * @param engineer the value for install.engineer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setEngineer(String engineer) {
        this.engineer = engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.engineer_tel
     *
     * @return the value of install.engineer_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getEngineerTel() {
        return engineerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.engineer_tel
     *
     * @param engineerTel the value for install.engineer_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setEngineerTel(String engineerTel) {
        this.engineerTel = engineerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.status
     *
     * @return the value of install.status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.status
     *
     * @param status the value for install.status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.estimated_arrival_time
     *
     * @return the value of install.estimated_arrival_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getEstimatedArrivalTime() {
        return estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.estimated_arrival_time
     *
     * @param estimatedArrivalTime the value for install.estimated_arrival_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setEstimatedArrivalTime(Date estimatedArrivalTime) {
        this.estimatedArrivalTime = estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.arrivaled_time
     *
     * @return the value of install.arrivaled_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getArrivaledTime() {
        return arrivaledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.arrivaled_time
     *
     * @param arrivaledTime the value for install.arrivaled_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setArrivaledTime(Date arrivaledTime) {
        this.arrivaledTime = arrivaledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.order_time
     *
     * @return the value of install.order_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.order_time
     *
     * @param orderTime the value for install.order_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.finishe_time
     *
     * @return the value of install.finishe_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Date getFinisheTime() {
        return finisheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.finishe_time
     *
     * @param finisheTime the value for install.finishe_time
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setFinisheTime(Date finisheTime) {
        this.finisheTime = finisheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hospital_name
     *
     * @return the value of install.hospital_name
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hospital_name
     *
     * @param hospitalName the value for install.hospital_name
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hospital_department
     *
     * @return the value of install.hospital_department
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHospitalDepartment() {
        return hospitalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hospital_department
     *
     * @param hospitalDepartment the value for install.hospital_department
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHospitalDepartment(String hospitalDepartment) {
        this.hospitalDepartment = hospitalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hospital_address
     *
     * @return the value of install.hospital_address
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHospitalAddress() {
        return hospitalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hospital_address
     *
     * @param hospitalAddress the value for install.hospital_address
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.zip_code
     *
     * @return the value of install.zip_code
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.zip_code
     *
     * @param zipCode the value for install.zip_code
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.product_type
     *
     * @return the value of install.product_type
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.product_type
     *
     * @param productType the value for install.product_type
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hospital_contact
     *
     * @return the value of install.hospital_contact
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHospitalContact() {
        return hospitalContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hospital_contact
     *
     * @param hospitalContact the value for install.hospital_contact
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHospitalContact(String hospitalContact) {
        this.hospitalContact = hospitalContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hospital_tel
     *
     * @return the value of install.hospital_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHospitalTel() {
        return hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hospital_tel
     *
     * @param hospitalTel the value for install.hospital_tel
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHospitalTel(String hospitalTel) {
        this.hospitalTel = hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.serial_number
     *
     * @return the value of install.serial_number
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.serial_number
     *
     * @param serialNumber the value for install.serial_number
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.product_model
     *
     * @return the value of install.product_model
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.product_model
     *
     * @param productModel the value for install.product_model
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setProductModel(String productModel) {
        this.productModel = productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.packaging
     *
     * @return the value of install.packaging
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getPackaging() {
        return packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.packaging
     *
     * @param packaging the value for install.packaging
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setPackaging(String packaging) {
        this.packaging = packaging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.out_appearance
     *
     * @return the value of install.out_appearance
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getOutAppearance() {
        return outAppearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.out_appearance
     *
     * @param outAppearance the value for install.out_appearance
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setOutAppearance(String outAppearance) {
        this.outAppearance = outAppearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.lis
     *
     * @return the value of install.lis
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getLis() {
        return lis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.lis
     *
     * @param lis the value for install.lis
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setLis(String lis) {
        this.lis = lis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.ip
     *
     * @return the value of install.ip
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.ip
     *
     * @param ip the value for install.ip
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.install_stauts
     *
     * @return the value of install.install_stauts
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getInstallStauts() {
        return installStauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.install_stauts
     *
     * @param installStauts the value for install.install_stauts
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setInstallStauts(String installStauts) {
        this.installStauts = installStauts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_return_purchase
     *
     * @return the value of install.is_return_purchase
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsReturnPurchase() {
        return isReturnPurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_return_purchase
     *
     * @param isReturnPurchase the value for install.is_return_purchase
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsReturnPurchase(Byte isReturnPurchase) {
        this.isReturnPurchase = isReturnPurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_monitor
     *
     * @return the value of install.is_monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsMonitor() {
        return isMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_monitor
     *
     * @param isMonitor the value for install.is_monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsMonitor(Byte isMonitor) {
        this.isMonitor = isMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_computer
     *
     * @return the value of install.is_computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsComputer() {
        return isComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_computer
     *
     * @param isComputer the value for install.is_computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsComputer(Byte isComputer) {
        this.isComputer = isComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_return_status
     *
     * @return the value of install.is_return_status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsReturnStatus() {
        return isReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_return_status
     *
     * @param isReturnStatus the value for install.is_return_status
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsReturnStatus(Byte isReturnStatus) {
        this.isReturnStatus = isReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_microscope
     *
     * @return the value of install.is_microscope
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsMicroscope() {
        return isMicroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_microscope
     *
     * @param isMicroscope the value for install.is_microscope
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsMicroscope(Byte isMicroscope) {
        this.isMicroscope = isMicroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_liquid
     *
     * @return the value of install.is_liquid
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsLiquid() {
        return isLiquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_liquid
     *
     * @param isLiquid the value for install.is_liquid
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsLiquid(Byte isLiquid) {
        this.isLiquid = isLiquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_pinch
     *
     * @return the value of install.is_pinch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsPinch() {
        return isPinch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_pinch
     *
     * @param isPinch the value for install.is_pinch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsPinch(Byte isPinch) {
        this.isPinch = isPinch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_auto_identify
     *
     * @return the value of install.is_auto_identify
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsAutoIdentify() {
        return isAutoIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_auto_identify
     *
     * @param isAutoIdentify the value for install.is_auto_identify
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsAutoIdentify(Byte isAutoIdentify) {
        this.isAutoIdentify = isAutoIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_step_motor
     *
     * @return the value of install.is_step_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsStepMotor() {
        return isStepMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_step_motor
     *
     * @param isStepMotor the value for install.is_step_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsStepMotor(Byte isStepMotor) {
        this.isStepMotor = isStepMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_micro_switch
     *
     * @return the value of install.is_micro_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsMicroSwitch() {
        return isMicroSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_micro_switch
     *
     * @param isMicroSwitch the value for install.is_micro_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsMicroSwitch(Byte isMicroSwitch) {
        this.isMicroSwitch = isMicroSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_gold
     *
     * @return the value of install.is_gold
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsGold() {
        return isGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_gold
     *
     * @param isGold the value for install.is_gold
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsGold(Byte isGold) {
        this.isGold = isGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_dc_motor
     *
     * @return the value of install.is_dc_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsDcMotor() {
        return isDcMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_dc_motor
     *
     * @param isDcMotor the value for install.is_dc_motor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsDcMotor(Byte isDcMotor) {
        this.isDcMotor = isDcMotor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_opto
     *
     * @return the value of install.is_opto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsOpto() {
        return isOpto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_opto
     *
     * @param isOpto the value for install.is_opto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsOpto(Byte isOpto) {
        this.isOpto = isOpto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_stool_trait
     *
     * @return the value of install.is_stool_trait
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsStoolTrait() {
        return isStoolTrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_stool_trait
     *
     * @param isStoolTrait the value for install.is_stool_trait
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsStoolTrait(Byte isStoolTrait) {
        this.isStoolTrait = isStoolTrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_peristaltic_pump
     *
     * @return the value of install.is_peristaltic_pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsPeristalticPump() {
        return isPeristalticPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_peristaltic_pump
     *
     * @param isPeristalticPump the value for install.is_peristaltic_pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsPeristalticPump(Byte isPeristalticPump) {
        this.isPeristalticPump = isPeristalticPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_piston pump
     *
     * @return the value of install.is_piston pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsPistonPump() {
        return isPistonPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_piston pump
     *
     * @param isPistonPump the value for install.is_piston pump
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsPistonPump(Byte isPistonPump) {
        this.isPistonPump = isPistonPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_stool_color
     *
     * @return the value of install.is_stool_color
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsStoolColor() {
        return isStoolColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_stool_color
     *
     * @param isStoolColor the value for install.is_stool_color
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsStoolColor(Byte isStoolColor) {
        this.isStoolColor = isStoolColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_import_sample
     *
     * @return the value of install.is_import_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsImportSample() {
        return isImportSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_import_sample
     *
     * @param isImportSample the value for install.is_import_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsImportSample(Byte isImportSample) {
        this.isImportSample = isImportSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_expose_sample
     *
     * @return the value of install.is_expose_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsExposeSample() {
        return isExposeSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_expose_sample
     *
     * @param isExposeSample the value for install.is_expose_sample
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsExposeSample(Byte isExposeSample) {
        this.isExposeSample = isExposeSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_cross_pollution
     *
     * @return the value of install.is_cross_pollution
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsCrossPollution() {
        return isCrossPollution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_cross_pollution
     *
     * @param isCrossPollution the value for install.is_cross_pollution
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsCrossPollution(Byte isCrossPollution) {
        this.isCrossPollution = isCrossPollution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_counting_pool
     *
     * @return the value of install.is_counting_pool
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsCountingPool() {
        return isCountingPool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_counting_pool
     *
     * @param isCountingPool the value for install.is_counting_pool
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsCountingPool(Byte isCountingPool) {
        this.isCountingPool = isCountingPool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_switch
     *
     * @return the value of install.is_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsSwitch() {
        return isSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_switch
     *
     * @param isSwitch the value for install.is_switch
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsSwitch(Byte isSwitch) {
        this.isSwitch = isSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_mix_system
     *
     * @return the value of install.is_mix_system
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsMixSystem() {
        return isMixSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_mix_system
     *
     * @param isMixSystem the value for install.is_mix_system
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsMixSystem(Byte isMixSystem) {
        this.isMixSystem = isMixSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_power_box
     *
     * @return the value of install.is_power_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsPowerBox() {
        return isPowerBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_power_box
     *
     * @param isPowerBox the value for install.is_power_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsPowerBox(Byte isPowerBox) {
        this.isPowerBox = isPowerBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_d15
     *
     * @return the value of install.is_d15
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsD15() {
        return isD15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_d15
     *
     * @param isD15 the value for install.is_d15
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsD15(Byte isD15) {
        this.isD15 = isD15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_electric_auto
     *
     * @return the value of install.is_electric_auto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsElectricAuto() {
        return isElectricAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_electric_auto
     *
     * @param isElectricAuto the value for install.is_electric_auto
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsElectricAuto(Byte isElectricAuto) {
        this.isElectricAuto = isElectricAuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_electirc_circuit
     *
     * @return the value of install.is_electirc_circuit
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsElectircCircuit() {
        return isElectircCircuit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_electirc_circuit
     *
     * @param isElectircCircuit the value for install.is_electirc_circuit
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsElectircCircuit(Byte isElectircCircuit) {
        this.isElectircCircuit = isElectircCircuit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.is_buck
     *
     * @return the value of install.is_buck
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public Byte getIsBuck() {
        return isBuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.is_buck
     *
     * @param isBuck the value for install.is_buck
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setIsBuck(Byte isBuck) {
        this.isBuck = isBuck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.zero_voltage
     *
     * @return the value of install.zero_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getZeroVoltage() {
        return zeroVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.zero_voltage
     *
     * @param zeroVoltage the value for install.zero_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setZeroVoltage(String zeroVoltage) {
        this.zeroVoltage = zeroVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.app_version
     *
     * @return the value of install.app_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.app_version
     *
     * @param appVersion the value for install.app_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hard_disk
     *
     * @return the value of install.hard_disk
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHardDisk() {
        return hardDisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hard_disk
     *
     * @param hardDisk the value for install.hard_disk
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHardDisk(String hardDisk) {
        this.hardDisk = hardDisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.computer_version
     *
     * @return the value of install.computer_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getComputerVersion() {
        return computerVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.computer_version
     *
     * @param computerVersion the value for install.computer_version
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setComputerVersion(String computerVersion) {
        this.computerVersion = computerVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.cpu
     *
     * @return the value of install.cpu
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getCpu() {
        return cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.cpu
     *
     * @param cpu the value for install.cpu
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setCpu(String cpu) {
        this.cpu = cpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.cd
     *
     * @return the value of install.cd
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.cd
     *
     * @param cd the value for install.cd
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setCd(String cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.ram
     *
     * @return the value of install.ram
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getRam() {
        return ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.ram
     *
     * @param ram the value for install.ram
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setRam(String ram) {
        this.ram = ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.supply_voltage
     *
     * @return the value of install.supply_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getSupplyVoltage() {
        return supplyVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.supply_voltage
     *
     * @param supplyVoltage the value for install.supply_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setSupplyVoltage(String supplyVoltage) {
        this.supplyVoltage = supplyVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.computer_voltage
     *
     * @return the value of install.computer_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getComputerVoltage() {
        return computerVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.computer_voltage
     *
     * @param computerVoltage the value for install.computer_voltage
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setComputerVoltage(String computerVoltage) {
        this.computerVoltage = computerVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.waste_liquid_bucket
     *
     * @return the value of install.waste_liquid_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getWasteLiquidBucket() {
        return wasteLiquidBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.waste_liquid_bucket
     *
     * @param wasteLiquidBucket the value for install.waste_liquid_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setWasteLiquidBucket(String wasteLiquidBucket) {
        this.wasteLiquidBucket = wasteLiquidBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.card_box
     *
     * @return the value of install.card_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getCardBox() {
        return cardBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.card_box
     *
     * @param cardBox the value for install.card_box
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setCardBox(String cardBox) {
        this.cardBox = cardBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.video_cable
     *
     * @return the value of install.video_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getVideoCable() {
        return videoCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.video_cable
     *
     * @param videoCable the value for install.video_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setVideoCable(String videoCable) {
        this.videoCable = videoCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.diluent_bucket
     *
     * @return the value of install.diluent_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getDiluentBucket() {
        return diluentBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.diluent_bucket
     *
     * @param diluentBucket the value for install.diluent_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setDiluentBucket(String diluentBucket) {
        this.diluentBucket = diluentBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.instrument_power_cable
     *
     * @return the value of install.instrument_power_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getInstrumentPowerCable() {
        return instrumentPowerCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.instrument_power_cable
     *
     * @param instrumentPowerCable the value for install.instrument_power_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setInstrumentPowerCable(String instrumentPowerCable) {
        this.instrumentPowerCable = instrumentPowerCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.usb_cable
     *
     * @return the value of install.usb_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getUsbCable() {
        return usbCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.usb_cable
     *
     * @param usbCable the value for install.usb_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setUsbCable(String usbCable) {
        this.usbCable = usbCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.clean_bucket
     *
     * @return the value of install.clean_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getCleanBucket() {
        return cleanBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.clean_bucket
     *
     * @param cleanBucket the value for install.clean_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setCleanBucket(String cleanBucket) {
        this.cleanBucket = cleanBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.computer_cable
     *
     * @return the value of install.computer_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getComputerCable() {
        return computerCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.computer_cable
     *
     * @param computerCable the value for install.computer_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setComputerCable(String computerCable) {
        this.computerCable = computerCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.certificate
     *
     * @return the value of install.certificate
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.certificate
     *
     * @param certificate the value for install.certificate
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.maintenance_bucket
     *
     * @return the value of install.maintenance_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getMaintenanceBucket() {
        return maintenanceBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.maintenance_bucket
     *
     * @param maintenanceBucket the value for install.maintenance_bucket
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setMaintenanceBucket(String maintenanceBucket) {
        this.maintenanceBucket = maintenanceBucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.monitor_cable
     *
     * @return the value of install.monitor_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getMonitorCable() {
        return monitorCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.monitor_cable
     *
     * @param monitorCable the value for install.monitor_cable
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setMonitorCable(String monitorCable) {
        this.monitorCable = monitorCable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.instrument
     *
     * @return the value of install.instrument
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.instrument
     *
     * @param instrument the value for install.instrument
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.manual
     *
     * @return the value of install.manual
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getManual() {
        return manual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.manual
     *
     * @param manual the value for install.manual
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setManual(String manual) {
        this.manual = manual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.computer
     *
     * @return the value of install.computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getComputer() {
        return computer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.computer
     *
     * @param computer the value for install.computer
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setComputer(String computer) {
        this.computer = computer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.monitor
     *
     * @return the value of install.monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getMonitor() {
        return monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.monitor
     *
     * @param monitor the value for install.monitor
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setMonitor(String monitor) {
        this.monitor = monitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.sample_holder
     *
     * @return the value of install.sample_holder
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getSampleHolder() {
        return sampleHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.sample_holder
     *
     * @param sampleHolder the value for install.sample_holder
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setSampleHolder(String sampleHolder) {
        this.sampleHolder = sampleHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.mouse
     *
     * @return the value of install.mouse
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getMouse() {
        return mouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.mouse
     *
     * @param mouse the value for install.mouse
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setMouse(String mouse) {
        this.mouse = mouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.keyboard
     *
     * @return the value of install.keyboard
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getKeyboard() {
        return keyboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.keyboard
     *
     * @param keyboard the value for install.keyboard
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setKeyboard(String keyboard) {
        this.keyboard = keyboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.supplies
     *
     * @return the value of install.supplies
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getSupplies() {
        return supplies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.supplies
     *
     * @param supplies the value for install.supplies
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setSupplies(String supplies) {
        this.supplies = supplies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.silicone_tube
     *
     * @return the value of install.silicone_tube
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getSiliconeTube() {
        return siliconeTube;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.silicone_tube
     *
     * @param siliconeTube the value for install.silicone_tube
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setSiliconeTube(String siliconeTube) {
        this.siliconeTube = siliconeTube;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.whether_doa
     *
     * @return the value of install.whether_doa
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getWhetherDoa() {
        return whetherDoa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.whether_doa
     *
     * @param whetherDoa the value for install.whether_doa
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setWhetherDoa(String whetherDoa) {
        this.whetherDoa = whetherDoa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.doa_information
     *
     * @return the value of install.doa_information
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getDoaInformation() {
        return doaInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.doa_information
     *
     * @param doaInformation the value for install.doa_information
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setDoaInformation(String doaInformation) {
        this.doaInformation = doaInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hardware
     *
     * @return the value of install.hardware
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHardware() {
        return hardware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hardware
     *
     * @param hardware the value for install.hardware
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHardware(String hardware) {
        this.hardware = hardware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.hardware_reason
     *
     * @return the value of install.hardware_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getHardwareReason() {
        return hardwareReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.hardware_reason
     *
     * @param hardwareReason the value for install.hardware_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setHardwareReason(String hardwareReason) {
        this.hardwareReason = hardwareReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.teacher_operator
     *
     * @return the value of install.teacher_operator
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getTeacherOperator() {
        return teacherOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.teacher_operator
     *
     * @param teacherOperator the value for install.teacher_operator
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setTeacherOperator(String teacherOperator) {
        this.teacherOperator = teacherOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.teacher_operator_reason
     *
     * @return the value of install.teacher_operator_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getTeacherOperatorReason() {
        return teacherOperatorReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.teacher_operator_reason
     *
     * @param teacherOperatorReason the value for install.teacher_operator_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setTeacherOperatorReason(String teacherOperatorReason) {
        this.teacherOperatorReason = teacherOperatorReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.operation_condition
     *
     * @return the value of install.operation_condition
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getOperationCondition() {
        return operationCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.operation_condition
     *
     * @param operationCondition the value for install.operation_condition
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setOperationCondition(String operationCondition) {
        this.operationCondition = operationCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.operation_condition_reason
     *
     * @return the value of install.operation_condition_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getOperationConditionReason() {
        return operationConditionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.operation_condition_reason
     *
     * @param operationConditionReason the value for install.operation_condition_reason
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setOperationConditionReason(String operationConditionReason) {
        this.operationConditionReason = operationConditionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.client_feedback
     *
     * @return the value of install.client_feedback
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getClientFeedback() {
        return clientFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.client_feedback
     *
     * @param clientFeedback the value for install.client_feedback
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setClientFeedback(String clientFeedback) {
        this.clientFeedback = clientFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install.remarks
     *
     * @return the value of install.remarks
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install.remarks
     *
     * @param remarks the value for install.remarks
     *
     * @mbg.generated Tue Feb 06 16:43:47 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}