package com.jinsong.model;

import java.util.Date;

public class Maintain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String engineer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.engineer_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String engineerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.status
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.estimated_arrival_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date estimatedArrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.arrivaled_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date arrivaledTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.order_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.finished_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Date finishedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.hospital_name
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.hospital_contact
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String hospitalContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.hospital_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String hospitalTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String productModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_insuranced
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isInsuranced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.current_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Integer currentSampleCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.sample_box_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String sampleBoxType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.reagent_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String reagentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_instrument
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isInstrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_computer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isComputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_microscope
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isMicroscope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_pump
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isPump;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_arm
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isArm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_stir
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isStir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_gold
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_sample
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_computer1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isComputer1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_computer2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isComputer2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_microscope1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isMicroscope1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_microscope2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isMicroscope2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_microscope3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isMicroscope3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_camera1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isCamera1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_camera2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isCamera2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_countpool1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isCountpool1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_countpool2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isCountpool2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_countpool3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isCountpool3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_arm1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isArm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_arm2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isArm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_arm3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isArm3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_arm4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isArm4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_liquid1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isLiquid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_liquid2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isLiquid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_sample1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isSample1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.is_sample2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private Byte isSample2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software5
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software6
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software7
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software8
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software9
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software10
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software11
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software12
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software13
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software14
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software15
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.software16
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String software16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.machine1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String machine1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.machine2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String machine2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maintain.remarks
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.id
     *
     * @return the value of maintain.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.id
     *
     * @param id the value for maintain.id
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.gmt_create
     *
     * @return the value of maintain.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.gmt_create
     *
     * @param gmtCreate the value for maintain.gmt_create
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.gmt_modified
     *
     * @return the value of maintain.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.gmt_modified
     *
     * @param gmtModified the value for maintain.gmt_modified
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.engineer
     *
     * @return the value of maintain.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.engineer
     *
     * @param engineer the value for maintain.engineer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setEngineer(String engineer) {
        this.engineer = engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.engineer_tel
     *
     * @return the value of maintain.engineer_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getEngineerTel() {
        return engineerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.engineer_tel
     *
     * @param engineerTel the value for maintain.engineer_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setEngineerTel(String engineerTel) {
        this.engineerTel = engineerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.status
     *
     * @return the value of maintain.status
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.status
     *
     * @param status the value for maintain.status
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.estimated_arrival_time
     *
     * @return the value of maintain.estimated_arrival_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getEstimatedArrivalTime() {
        return estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.estimated_arrival_time
     *
     * @param estimatedArrivalTime the value for maintain.estimated_arrival_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setEstimatedArrivalTime(Date estimatedArrivalTime) {
        this.estimatedArrivalTime = estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.arrivaled_time
     *
     * @return the value of maintain.arrivaled_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getArrivaledTime() {
        return arrivaledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.arrivaled_time
     *
     * @param arrivaledTime the value for maintain.arrivaled_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setArrivaledTime(Date arrivaledTime) {
        this.arrivaledTime = arrivaledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.order_time
     *
     * @return the value of maintain.order_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.order_time
     *
     * @param orderTime the value for maintain.order_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.finished_time
     *
     * @return the value of maintain.finished_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Date getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.finished_time
     *
     * @param finishedTime the value for maintain.finished_time
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setFinishedTime(Date finishedTime) {
        this.finishedTime = finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.hospital_name
     *
     * @return the value of maintain.hospital_name
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.hospital_name
     *
     * @param hospitalName the value for maintain.hospital_name
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.hospital_contact
     *
     * @return the value of maintain.hospital_contact
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getHospitalContact() {
        return hospitalContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.hospital_contact
     *
     * @param hospitalContact the value for maintain.hospital_contact
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setHospitalContact(String hospitalContact) {
        this.hospitalContact = hospitalContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.hospital_tel
     *
     * @return the value of maintain.hospital_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getHospitalTel() {
        return hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.hospital_tel
     *
     * @param hospitalTel the value for maintain.hospital_tel
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setHospitalTel(String hospitalTel) {
        this.hospitalTel = hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.serial_number
     *
     * @return the value of maintain.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.serial_number
     *
     * @param serialNumber the value for maintain.serial_number
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.product_model
     *
     * @return the value of maintain.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.product_model
     *
     * @param productModel the value for maintain.product_model
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setProductModel(String productModel) {
        this.productModel = productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_insuranced
     *
     * @return the value of maintain.is_insuranced
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsInsuranced() {
        return isInsuranced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_insuranced
     *
     * @param isInsuranced the value for maintain.is_insuranced
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsInsuranced(Byte isInsuranced) {
        this.isInsuranced = isInsuranced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.current_sample_count
     *
     * @return the value of maintain.current_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Integer getCurrentSampleCount() {
        return currentSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.current_sample_count
     *
     * @param currentSampleCount the value for maintain.current_sample_count
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setCurrentSampleCount(Integer currentSampleCount) {
        this.currentSampleCount = currentSampleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.sample_box_type
     *
     * @return the value of maintain.sample_box_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSampleBoxType() {
        return sampleBoxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.sample_box_type
     *
     * @param sampleBoxType the value for maintain.sample_box_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSampleBoxType(String sampleBoxType) {
        this.sampleBoxType = sampleBoxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.reagent_type
     *
     * @return the value of maintain.reagent_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getReagentType() {
        return reagentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.reagent_type
     *
     * @param reagentType the value for maintain.reagent_type
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setReagentType(String reagentType) {
        this.reagentType = reagentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_instrument
     *
     * @return the value of maintain.is_instrument
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsInstrument() {
        return isInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_instrument
     *
     * @param isInstrument the value for maintain.is_instrument
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsInstrument(Byte isInstrument) {
        this.isInstrument = isInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_computer
     *
     * @return the value of maintain.is_computer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsComputer() {
        return isComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_computer
     *
     * @param isComputer the value for maintain.is_computer
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsComputer(Byte isComputer) {
        this.isComputer = isComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_microscope
     *
     * @return the value of maintain.is_microscope
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsMicroscope() {
        return isMicroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_microscope
     *
     * @param isMicroscope the value for maintain.is_microscope
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsMicroscope(Byte isMicroscope) {
        this.isMicroscope = isMicroscope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_pump
     *
     * @return the value of maintain.is_pump
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsPump() {
        return isPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_pump
     *
     * @param isPump the value for maintain.is_pump
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsPump(Byte isPump) {
        this.isPump = isPump;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_arm
     *
     * @return the value of maintain.is_arm
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsArm() {
        return isArm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_arm
     *
     * @param isArm the value for maintain.is_arm
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsArm(Byte isArm) {
        this.isArm = isArm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_stir
     *
     * @return the value of maintain.is_stir
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsStir() {
        return isStir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_stir
     *
     * @param isStir the value for maintain.is_stir
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsStir(Byte isStir) {
        this.isStir = isStir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_gold
     *
     * @return the value of maintain.is_gold
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsGold() {
        return isGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_gold
     *
     * @param isGold the value for maintain.is_gold
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsGold(Byte isGold) {
        this.isGold = isGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_sample
     *
     * @return the value of maintain.is_sample
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsSample() {
        return isSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_sample
     *
     * @param isSample the value for maintain.is_sample
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsSample(Byte isSample) {
        this.isSample = isSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_computer1
     *
     * @return the value of maintain.is_computer1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsComputer1() {
        return isComputer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_computer1
     *
     * @param isComputer1 the value for maintain.is_computer1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsComputer1(Byte isComputer1) {
        this.isComputer1 = isComputer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_computer2
     *
     * @return the value of maintain.is_computer2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsComputer2() {
        return isComputer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_computer2
     *
     * @param isComputer2 the value for maintain.is_computer2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsComputer2(Byte isComputer2) {
        this.isComputer2 = isComputer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_microscope1
     *
     * @return the value of maintain.is_microscope1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsMicroscope1() {
        return isMicroscope1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_microscope1
     *
     * @param isMicroscope1 the value for maintain.is_microscope1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsMicroscope1(Byte isMicroscope1) {
        this.isMicroscope1 = isMicroscope1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_microscope2
     *
     * @return the value of maintain.is_microscope2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsMicroscope2() {
        return isMicroscope2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_microscope2
     *
     * @param isMicroscope2 the value for maintain.is_microscope2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsMicroscope2(Byte isMicroscope2) {
        this.isMicroscope2 = isMicroscope2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_microscope3
     *
     * @return the value of maintain.is_microscope3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsMicroscope3() {
        return isMicroscope3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_microscope3
     *
     * @param isMicroscope3 the value for maintain.is_microscope3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsMicroscope3(Byte isMicroscope3) {
        this.isMicroscope3 = isMicroscope3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_camera1
     *
     * @return the value of maintain.is_camera1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsCamera1() {
        return isCamera1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_camera1
     *
     * @param isCamera1 the value for maintain.is_camera1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsCamera1(Byte isCamera1) {
        this.isCamera1 = isCamera1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_camera2
     *
     * @return the value of maintain.is_camera2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsCamera2() {
        return isCamera2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_camera2
     *
     * @param isCamera2 the value for maintain.is_camera2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsCamera2(Byte isCamera2) {
        this.isCamera2 = isCamera2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_countpool1
     *
     * @return the value of maintain.is_countpool1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsCountpool1() {
        return isCountpool1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_countpool1
     *
     * @param isCountpool1 the value for maintain.is_countpool1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsCountpool1(Byte isCountpool1) {
        this.isCountpool1 = isCountpool1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_countpool2
     *
     * @return the value of maintain.is_countpool2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsCountpool2() {
        return isCountpool2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_countpool2
     *
     * @param isCountpool2 the value for maintain.is_countpool2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsCountpool2(Byte isCountpool2) {
        this.isCountpool2 = isCountpool2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_countpool3
     *
     * @return the value of maintain.is_countpool3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsCountpool3() {
        return isCountpool3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_countpool3
     *
     * @param isCountpool3 the value for maintain.is_countpool3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsCountpool3(Byte isCountpool3) {
        this.isCountpool3 = isCountpool3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_arm1
     *
     * @return the value of maintain.is_arm1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsArm1() {
        return isArm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_arm1
     *
     * @param isArm1 the value for maintain.is_arm1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsArm1(Byte isArm1) {
        this.isArm1 = isArm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_arm2
     *
     * @return the value of maintain.is_arm2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsArm2() {
        return isArm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_arm2
     *
     * @param isArm2 the value for maintain.is_arm2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsArm2(Byte isArm2) {
        this.isArm2 = isArm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_arm3
     *
     * @return the value of maintain.is_arm3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsArm3() {
        return isArm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_arm3
     *
     * @param isArm3 the value for maintain.is_arm3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsArm3(Byte isArm3) {
        this.isArm3 = isArm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_arm4
     *
     * @return the value of maintain.is_arm4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsArm4() {
        return isArm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_arm4
     *
     * @param isArm4 the value for maintain.is_arm4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsArm4(Byte isArm4) {
        this.isArm4 = isArm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_liquid1
     *
     * @return the value of maintain.is_liquid1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsLiquid1() {
        return isLiquid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_liquid1
     *
     * @param isLiquid1 the value for maintain.is_liquid1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsLiquid1(Byte isLiquid1) {
        this.isLiquid1 = isLiquid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_liquid2
     *
     * @return the value of maintain.is_liquid2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsLiquid2() {
        return isLiquid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_liquid2
     *
     * @param isLiquid2 the value for maintain.is_liquid2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsLiquid2(Byte isLiquid2) {
        this.isLiquid2 = isLiquid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_sample1
     *
     * @return the value of maintain.is_sample1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsSample1() {
        return isSample1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_sample1
     *
     * @param isSample1 the value for maintain.is_sample1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsSample1(Byte isSample1) {
        this.isSample1 = isSample1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.is_sample2
     *
     * @return the value of maintain.is_sample2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public Byte getIsSample2() {
        return isSample2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.is_sample2
     *
     * @param isSample2 the value for maintain.is_sample2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setIsSample2(Byte isSample2) {
        this.isSample2 = isSample2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software1
     *
     * @return the value of maintain.software1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware1() {
        return software1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software1
     *
     * @param software1 the value for maintain.software1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware1(String software1) {
        this.software1 = software1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software2
     *
     * @return the value of maintain.software2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware2() {
        return software2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software2
     *
     * @param software2 the value for maintain.software2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware2(String software2) {
        this.software2 = software2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software3
     *
     * @return the value of maintain.software3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware3() {
        return software3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software3
     *
     * @param software3 the value for maintain.software3
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware3(String software3) {
        this.software3 = software3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software4
     *
     * @return the value of maintain.software4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware4() {
        return software4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software4
     *
     * @param software4 the value for maintain.software4
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware4(String software4) {
        this.software4 = software4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software5
     *
     * @return the value of maintain.software5
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware5() {
        return software5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software5
     *
     * @param software5 the value for maintain.software5
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware5(String software5) {
        this.software5 = software5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software6
     *
     * @return the value of maintain.software6
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware6() {
        return software6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software6
     *
     * @param software6 the value for maintain.software6
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware6(String software6) {
        this.software6 = software6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software7
     *
     * @return the value of maintain.software7
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware7() {
        return software7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software7
     *
     * @param software7 the value for maintain.software7
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware7(String software7) {
        this.software7 = software7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software8
     *
     * @return the value of maintain.software8
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware8() {
        return software8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software8
     *
     * @param software8 the value for maintain.software8
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware8(String software8) {
        this.software8 = software8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software9
     *
     * @return the value of maintain.software9
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware9() {
        return software9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software9
     *
     * @param software9 the value for maintain.software9
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware9(String software9) {
        this.software9 = software9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software10
     *
     * @return the value of maintain.software10
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware10() {
        return software10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software10
     *
     * @param software10 the value for maintain.software10
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware10(String software10) {
        this.software10 = software10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software11
     *
     * @return the value of maintain.software11
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware11() {
        return software11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software11
     *
     * @param software11 the value for maintain.software11
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware11(String software11) {
        this.software11 = software11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software12
     *
     * @return the value of maintain.software12
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware12() {
        return software12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software12
     *
     * @param software12 the value for maintain.software12
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware12(String software12) {
        this.software12 = software12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software13
     *
     * @return the value of maintain.software13
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware13() {
        return software13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software13
     *
     * @param software13 the value for maintain.software13
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware13(String software13) {
        this.software13 = software13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software14
     *
     * @return the value of maintain.software14
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware14() {
        return software14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software14
     *
     * @param software14 the value for maintain.software14
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware14(String software14) {
        this.software14 = software14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software15
     *
     * @return the value of maintain.software15
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware15() {
        return software15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software15
     *
     * @param software15 the value for maintain.software15
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware15(String software15) {
        this.software15 = software15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.software16
     *
     * @return the value of maintain.software16
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getSoftware16() {
        return software16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.software16
     *
     * @param software16 the value for maintain.software16
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setSoftware16(String software16) {
        this.software16 = software16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.machine1
     *
     * @return the value of maintain.machine1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getMachine1() {
        return machine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.machine1
     *
     * @param machine1 the value for maintain.machine1
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setMachine1(String machine1) {
        this.machine1 = machine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.machine2
     *
     * @return the value of maintain.machine2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getMachine2() {
        return machine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.machine2
     *
     * @param machine2 the value for maintain.machine2
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setMachine2(String machine2) {
        this.machine2 = machine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maintain.remarks
     *
     * @return the value of maintain.remarks
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maintain.remarks
     *
     * @param remarks the value for maintain.remarks
     *
     * @mbg.generated Thu Feb 08 10:37:57 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}