package com.jinsong.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNull() {
            addCriterion("serial_number is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNotNull() {
            addCriterion("serial_number is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberEqualTo(String value) {
            addCriterion("serial_number =", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotEqualTo(String value) {
            addCriterion("serial_number <>", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThan(String value) {
            addCriterion("serial_number >", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThanOrEqualTo(String value) {
            addCriterion("serial_number >=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThan(String value) {
            addCriterion("serial_number <", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThanOrEqualTo(String value) {
            addCriterion("serial_number <=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLike(String value) {
            addCriterion("serial_number like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotLike(String value) {
            addCriterion("serial_number not like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIn(List<String> values) {
            addCriterion("serial_number in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotIn(List<String> values) {
            addCriterion("serial_number not in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberBetween(String value1, String value2) {
            addCriterion("serial_number between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotBetween(String value1, String value2) {
            addCriterion("serial_number not between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductModelIsNull() {
            addCriterion("product_model is null");
            return (Criteria) this;
        }

        public Criteria andProductModelIsNotNull() {
            addCriterion("product_model is not null");
            return (Criteria) this;
        }

        public Criteria andProductModelEqualTo(String value) {
            addCriterion("product_model =", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotEqualTo(String value) {
            addCriterion("product_model <>", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelGreaterThan(String value) {
            addCriterion("product_model >", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelGreaterThanOrEqualTo(String value) {
            addCriterion("product_model >=", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLessThan(String value) {
            addCriterion("product_model <", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLessThanOrEqualTo(String value) {
            addCriterion("product_model <=", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLike(String value) {
            addCriterion("product_model like", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotLike(String value) {
            addCriterion("product_model not like", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelIn(List<String> values) {
            addCriterion("product_model in", values, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotIn(List<String> values) {
            addCriterion("product_model not in", values, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelBetween(String value1, String value2) {
            addCriterion("product_model between", value1, value2, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotBetween(String value1, String value2) {
            addCriterion("product_model not between", value1, value2, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNull() {
            addCriterion("hospital_name is null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNotNull() {
            addCriterion("hospital_name is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameEqualTo(String value) {
            addCriterion("hospital_name =", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotEqualTo(String value) {
            addCriterion("hospital_name <>", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThan(String value) {
            addCriterion("hospital_name >", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_name >=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThan(String value) {
            addCriterion("hospital_name <", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThanOrEqualTo(String value) {
            addCriterion("hospital_name <=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLike(String value) {
            addCriterion("hospital_name like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotLike(String value) {
            addCriterion("hospital_name not like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIn(List<String> values) {
            addCriterion("hospital_name in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotIn(List<String> values) {
            addCriterion("hospital_name not in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameBetween(String value1, String value2) {
            addCriterion("hospital_name between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotBetween(String value1, String value2) {
            addCriterion("hospital_name not between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIsNull() {
            addCriterion("hospital_address is null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIsNotNull() {
            addCriterion("hospital_address is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressEqualTo(String value) {
            addCriterion("hospital_address =", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotEqualTo(String value) {
            addCriterion("hospital_address <>", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressGreaterThan(String value) {
            addCriterion("hospital_address >", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_address >=", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLessThan(String value) {
            addCriterion("hospital_address <", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLessThanOrEqualTo(String value) {
            addCriterion("hospital_address <=", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressLike(String value) {
            addCriterion("hospital_address like", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotLike(String value) {
            addCriterion("hospital_address not like", value, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressIn(List<String> values) {
            addCriterion("hospital_address in", values, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotIn(List<String> values) {
            addCriterion("hospital_address not in", values, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressBetween(String value1, String value2) {
            addCriterion("hospital_address between", value1, value2, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalAddressNotBetween(String value1, String value2) {
            addCriterion("hospital_address not between", value1, value2, "hospitalAddress");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentIsNull() {
            addCriterion("hospital_department is null");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentIsNotNull() {
            addCriterion("hospital_department is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentEqualTo(String value) {
            addCriterion("hospital_department =", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentNotEqualTo(String value) {
            addCriterion("hospital_department <>", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentGreaterThan(String value) {
            addCriterion("hospital_department >", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_department >=", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentLessThan(String value) {
            addCriterion("hospital_department <", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentLessThanOrEqualTo(String value) {
            addCriterion("hospital_department <=", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentLike(String value) {
            addCriterion("hospital_department like", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentNotLike(String value) {
            addCriterion("hospital_department not like", value, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentIn(List<String> values) {
            addCriterion("hospital_department in", values, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentNotIn(List<String> values) {
            addCriterion("hospital_department not in", values, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentBetween(String value1, String value2) {
            addCriterion("hospital_department between", value1, value2, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalDepartmentNotBetween(String value1, String value2) {
            addCriterion("hospital_department not between", value1, value2, "hospitalDepartment");
            return (Criteria) this;
        }

        public Criteria andHospitalContactIsNull() {
            addCriterion("hospital_contact is null");
            return (Criteria) this;
        }

        public Criteria andHospitalContactIsNotNull() {
            addCriterion("hospital_contact is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalContactEqualTo(String value) {
            addCriterion("hospital_contact =", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactNotEqualTo(String value) {
            addCriterion("hospital_contact <>", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactGreaterThan(String value) {
            addCriterion("hospital_contact >", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_contact >=", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactLessThan(String value) {
            addCriterion("hospital_contact <", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactLessThanOrEqualTo(String value) {
            addCriterion("hospital_contact <=", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactLike(String value) {
            addCriterion("hospital_contact like", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactNotLike(String value) {
            addCriterion("hospital_contact not like", value, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactIn(List<String> values) {
            addCriterion("hospital_contact in", values, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactNotIn(List<String> values) {
            addCriterion("hospital_contact not in", values, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactBetween(String value1, String value2) {
            addCriterion("hospital_contact between", value1, value2, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalContactNotBetween(String value1, String value2) {
            addCriterion("hospital_contact not between", value1, value2, "hospitalContact");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIsNull() {
            addCriterion("hospital_tel is null");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIsNotNull() {
            addCriterion("hospital_tel is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalTelEqualTo(String value) {
            addCriterion("hospital_tel =", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotEqualTo(String value) {
            addCriterion("hospital_tel <>", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelGreaterThan(String value) {
            addCriterion("hospital_tel >", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_tel >=", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLessThan(String value) {
            addCriterion("hospital_tel <", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLessThanOrEqualTo(String value) {
            addCriterion("hospital_tel <=", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLike(String value) {
            addCriterion("hospital_tel like", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotLike(String value) {
            addCriterion("hospital_tel not like", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIn(List<String> values) {
            addCriterion("hospital_tel in", values, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotIn(List<String> values) {
            addCriterion("hospital_tel not in", values, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelBetween(String value1, String value2) {
            addCriterion("hospital_tel between", value1, value2, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotBetween(String value1, String value2) {
            addCriterion("hospital_tel not between", value1, value2, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeIsNull() {
            addCriterion("status_change_time is null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeIsNotNull() {
            addCriterion("status_change_time is not null");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeEqualTo(Date value) {
            addCriterion("status_change_time =", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeNotEqualTo(Date value) {
            addCriterion("status_change_time <>", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeGreaterThan(Date value) {
            addCriterion("status_change_time >", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("status_change_time >=", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeLessThan(Date value) {
            addCriterion("status_change_time <", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeLessThanOrEqualTo(Date value) {
            addCriterion("status_change_time <=", value, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeIn(List<Date> values) {
            addCriterion("status_change_time in", values, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeNotIn(List<Date> values) {
            addCriterion("status_change_time not in", values, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeBetween(Date value1, Date value2) {
            addCriterion("status_change_time between", value1, value2, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusChangeTimeNotBetween(Date value1, Date value2) {
            addCriterion("status_change_time not between", value1, value2, "statusChangeTime");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorIsNull() {
            addCriterion("status_operator is null");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorIsNotNull() {
            addCriterion("status_operator is not null");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorEqualTo(String value) {
            addCriterion("status_operator =", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorNotEqualTo(String value) {
            addCriterion("status_operator <>", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorGreaterThan(String value) {
            addCriterion("status_operator >", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("status_operator >=", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorLessThan(String value) {
            addCriterion("status_operator <", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorLessThanOrEqualTo(String value) {
            addCriterion("status_operator <=", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorLike(String value) {
            addCriterion("status_operator like", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorNotLike(String value) {
            addCriterion("status_operator not like", value, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorIn(List<String> values) {
            addCriterion("status_operator in", values, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorNotIn(List<String> values) {
            addCriterion("status_operator not in", values, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorBetween(String value1, String value2) {
            addCriterion("status_operator between", value1, value2, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andStatusOperatorNotBetween(String value1, String value2) {
            addCriterion("status_operator not between", value1, value2, "statusOperator");
            return (Criteria) this;
        }

        public Criteria andRepairTimesIsNull() {
            addCriterion("repair_times is null");
            return (Criteria) this;
        }

        public Criteria andRepairTimesIsNotNull() {
            addCriterion("repair_times is not null");
            return (Criteria) this;
        }

        public Criteria andRepairTimesEqualTo(Integer value) {
            addCriterion("repair_times =", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesNotEqualTo(Integer value) {
            addCriterion("repair_times <>", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesGreaterThan(Integer value) {
            addCriterion("repair_times >", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("repair_times >=", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesLessThan(Integer value) {
            addCriterion("repair_times <", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesLessThanOrEqualTo(Integer value) {
            addCriterion("repair_times <=", value, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesIn(List<Integer> values) {
            addCriterion("repair_times in", values, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesNotIn(List<Integer> values) {
            addCriterion("repair_times not in", values, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesBetween(Integer value1, Integer value2) {
            addCriterion("repair_times between", value1, value2, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andRepairTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("repair_times not between", value1, value2, "repairTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesIsNull() {
            addCriterion("maintenance_times is null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesIsNotNull() {
            addCriterion("maintenance_times is not null");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesEqualTo(Integer value) {
            addCriterion("maintenance_times =", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesNotEqualTo(Integer value) {
            addCriterion("maintenance_times <>", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesGreaterThan(Integer value) {
            addCriterion("maintenance_times >", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("maintenance_times >=", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesLessThan(Integer value) {
            addCriterion("maintenance_times <", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesLessThanOrEqualTo(Integer value) {
            addCriterion("maintenance_times <=", value, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesIn(List<Integer> values) {
            addCriterion("maintenance_times in", values, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesNotIn(List<Integer> values) {
            addCriterion("maintenance_times not in", values, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesBetween(Integer value1, Integer value2) {
            addCriterion("maintenance_times between", value1, value2, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMaintenanceTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("maintenance_times not between", value1, value2, "maintenanceTimes");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountIsNull() {
            addCriterion("month_sample_count is null");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountIsNotNull() {
            addCriterion("month_sample_count is not null");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountEqualTo(Integer value) {
            addCriterion("month_sample_count =", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountNotEqualTo(Integer value) {
            addCriterion("month_sample_count <>", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountGreaterThan(Integer value) {
            addCriterion("month_sample_count >", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_sample_count >=", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountLessThan(Integer value) {
            addCriterion("month_sample_count <", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountLessThanOrEqualTo(Integer value) {
            addCriterion("month_sample_count <=", value, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountIn(List<Integer> values) {
            addCriterion("month_sample_count in", values, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountNotIn(List<Integer> values) {
            addCriterion("month_sample_count not in", values, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountBetween(Integer value1, Integer value2) {
            addCriterion("month_sample_count between", value1, value2, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andMonthSampleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("month_sample_count not between", value1, value2, "monthSampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountIsNull() {
            addCriterion("day_sample_count is null");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountIsNotNull() {
            addCriterion("day_sample_count is not null");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountEqualTo(Integer value) {
            addCriterion("day_sample_count =", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountNotEqualTo(Integer value) {
            addCriterion("day_sample_count <>", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountGreaterThan(Integer value) {
            addCriterion("day_sample_count >", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_sample_count >=", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountLessThan(Integer value) {
            addCriterion("day_sample_count <", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountLessThanOrEqualTo(Integer value) {
            addCriterion("day_sample_count <=", value, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountIn(List<Integer> values) {
            addCriterion("day_sample_count in", values, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountNotIn(List<Integer> values) {
            addCriterion("day_sample_count not in", values, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountBetween(Integer value1, Integer value2) {
            addCriterion("day_sample_count between", value1, value2, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andDaySampleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("day_sample_count not between", value1, value2, "daySampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountIsNull() {
            addCriterion("current_sample_count is null");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountIsNotNull() {
            addCriterion("current_sample_count is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountEqualTo(Integer value) {
            addCriterion("current_sample_count =", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountNotEqualTo(Integer value) {
            addCriterion("current_sample_count <>", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountGreaterThan(Integer value) {
            addCriterion("current_sample_count >", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_sample_count >=", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountLessThan(Integer value) {
            addCriterion("current_sample_count <", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountLessThanOrEqualTo(Integer value) {
            addCriterion("current_sample_count <=", value, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountIn(List<Integer> values) {
            addCriterion("current_sample_count in", values, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountNotIn(List<Integer> values) {
            addCriterion("current_sample_count not in", values, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountBetween(Integer value1, Integer value2) {
            addCriterion("current_sample_count between", value1, value2, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andCurrentSampleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("current_sample_count not between", value1, value2, "currentSampleCount");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNull() {
            addCriterion("district is null");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNotNull() {
            addCriterion("district is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictEqualTo(String value) {
            addCriterion("district =", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotEqualTo(String value) {
            addCriterion("district <>", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThan(String value) {
            addCriterion("district >", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("district >=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThan(String value) {
            addCriterion("district <", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThanOrEqualTo(String value) {
            addCriterion("district <=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLike(String value) {
            addCriterion("district like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotLike(String value) {
            addCriterion("district not like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictIn(List<String> values) {
            addCriterion("district in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotIn(List<String> values) {
            addCriterion("district not in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictBetween(String value1, String value2) {
            addCriterion("district between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotBetween(String value1, String value2) {
            addCriterion("district not between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNull() {
            addCriterion("ship_date is null");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNotNull() {
            addCriterion("ship_date is not null");
            return (Criteria) this;
        }

        public Criteria andShipDateEqualTo(Date value) {
            addCriterion("ship_date =", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotEqualTo(Date value) {
            addCriterion("ship_date <>", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThan(Date value) {
            addCriterion("ship_date >", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ship_date >=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThan(Date value) {
            addCriterion("ship_date <", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThanOrEqualTo(Date value) {
            addCriterion("ship_date <=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateIn(List<Date> values) {
            addCriterion("ship_date in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotIn(List<Date> values) {
            addCriterion("ship_date not in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateBetween(Date value1, Date value2) {
            addCriterion("ship_date between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotBetween(Date value1, Date value2) {
            addCriterion("ship_date not between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 06 11:59:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Tue Feb 06 11:59:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}