package com.jinsong.model;

import java.util.Date;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.id
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.gmt_create
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.gmt_modified
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.attendance_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String attendanceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.work_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String workTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.hospital_name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.product_model
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String productModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.error
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.solution
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String solution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.finished
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.finished_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String finishedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.remark
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.id
     *
     * @return the value of work.id
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.id
     *
     * @param id the value for work.id
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.gmt_create
     *
     * @return the value of work.gmt_create
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.gmt_create
     *
     * @param gmtCreate the value for work.gmt_create
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.gmt_modified
     *
     * @return the value of work.gmt_modified
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.gmt_modified
     *
     * @param gmtModified the value for work.gmt_modified
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.name
     *
     * @return the value of work.name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.name
     *
     * @param name the value for work.name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.attendance_time
     *
     * @return the value of work.attendance_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getAttendanceTime() {
        return attendanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.attendance_time
     *
     * @param attendanceTime the value for work.attendance_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setAttendanceTime(String attendanceTime) {
        this.attendanceTime = attendanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.work_time
     *
     * @return the value of work.work_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.work_time
     *
     * @param workTime the value for work.work_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setWorkTime(String workTime) {
        this.workTime = workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.hospital_name
     *
     * @return the value of work.hospital_name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.hospital_name
     *
     * @param hospitalName the value for work.hospital_name
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.product_model
     *
     * @return the value of work.product_model
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.product_model
     *
     * @param productModel the value for work.product_model
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setProductModel(String productModel) {
        this.productModel = productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.error
     *
     * @return the value of work.error
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.error
     *
     * @param error the value for work.error
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setError(String error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.solution
     *
     * @return the value of work.solution
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.solution
     *
     * @param solution the value for work.solution
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setSolution(String solution) {
        this.solution = solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.finished
     *
     * @return the value of work.finished
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.finished
     *
     * @param finished the value for work.finished
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setFinished(String finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.finished_time
     *
     * @return the value of work.finished_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.finished_time
     *
     * @param finishedTime the value for work.finished_time
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setFinishedTime(String finishedTime) {
        this.finishedTime = finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.remark
     *
     * @return the value of work.remark
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.remark
     *
     * @param remark the value for work.remark
     *
     * @mbg.generated Fri May 11 11:16:06 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}